#!/usr/bin/env python3
"""Copies the sync design's test data into the engine (SYNC.md 7.1, 10 E):
ref/vectors.h -> mac/CedarCore/SyncVectors.h (unchanged but for a first line)
and ref/fixtures/*.cdl -> mac/CedarCore/SyncFixtures.h (one string literal per
line, so no compiler's literal size limit is reached). The files in ref/ are
the contract; never edit the generated ones by hand.

    python3 mac/Tools/make-sync-vectors.py <path to the design's ref/ folder>
"""
import os
import sys

ref = sys.argv[1] if len(sys.argv) > 1 else "ref"
here = os.path.dirname(os.path.abspath(__file__))
core = os.path.join(here, "..", "CedarCore")


def lit(b: bytes) -> str:
    out = '"'
    for x in b:
        ch = chr(x)
        if ch == '"':
            out += '\\"'
        elif ch == '\\':
            out += '\\\\'
        elif ch == '\n':
            out += '\\n'
        elif ch == '\r':
            out += '\\r'
        elif ch == '\t':
            out += '\\t'
        elif 32 <= x < 127 and ch != '?':
            out += ch
        else:
            out += '\\x%02x""' % x
    return out + '"'


with open(os.path.join(ref, "vectors.h"), encoding="utf-8") as f:
    vectors = f.read()
with open(os.path.join(core, "SyncVectors.h"), "w", encoding="utf-8", newline="\n") as f:
    f.write("// Copied from the sync design's ref/vectors.h by mac/Tools/make-sync-vectors.py. Do not edit.\n")
    f.write(vectors)

names = sorted(n for n in os.listdir(os.path.join(ref, "fixtures")) if n.endswith(".cdl"))
L = ["// ref/fixtures/*.cdl (SYNC.md 7.1.5), generated by mac/Tools/make-sync-vectors.py. Do not edit.",
     "// Each file is its lines in order (joined, they are the file's exact bytes).",
     "#pragma once", ""]
for n in names:
    data = open(os.path.join(ref, "fixtures", n), "rb").read()
    ident = "kFixture_" + n[:-4].replace("-", "_")
    L.append("static const char* const %s[] = {" % ident)
    for line in data.splitlines(keepends=True):
        L.append("  " + lit(line) + ",")
    L.append("  nullptr };")
    L.append("")
L.append("struct SyncFixture { const char* file; const char* const* lines; };")
L.append("static const SyncFixture kSyncFixtures[] = {")
for n in names:
    L.append('  { "%s", kFixture_%s },' % (n, n[:-4].replace("-", "_")))
L.append("};")
L.append("")
with open(os.path.join(core, "SyncFixtures.h"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(L))
print("wrote SyncVectors.h and SyncFixtures.h")
