#!/usr/bin/env python3
"""Copies the classroom test vectors into the core (CLASSROOM.md 7.1, 10 E):
tests/classroom/vectors.json -> mac/CedarCore/ClassroomVectors.h, the file's
text as string literals of one line each (no compiler's literal size limit is
reached), which the self-test parses with the sync engine's JSON reader. The
JSON file is the contract; never edit the generated one by hand.

    python3 mac/Tools/make-classroom-vectors.py [tests/classroom/vectors.json]
"""
import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", "..", "tests", "classroom", "vectors.json")
out = os.path.join(here, "..", "CedarCore", "ClassroomVectors.h")


def lit(b: bytes) -> str:
    s = '"'
    for x in b:
        if x == 0x22:
            s += '\\"'
        elif x == 0x5C:
            s += '\\\\'
        elif x == 0x0A:
            s += '\\n'
        elif x < 0x20 or x >= 0x7F:
            s += '\\%03o' % x
        else:
            s += chr(x)
    return s + '"'


data = open(src, "rb").read()
lines = data.split(b"\n")
with open(out, "w") as f:
    f.write("// Generated by mac/Tools/make-classroom-vectors.py from tests/classroom/vectors.json\n")
    f.write("// (CLASSROOM.md 7.1). Don't edit: regenerate.\n#pragma once\n\nnamespace clclass {\nnamespace test {\n\n")
    f.write("// The file's lines, each with its newline, then nullptr.\n")
    f.write("static const char* const kVectorLines[] = {\n")
    for i, line in enumerate(lines):
        if i == len(lines) - 1 and not line:
            break
        f.write("\t" + lit(line + (b"\n" if i < len(lines) - 1 else b"")) + ",\n")
    f.write("\tnullptr,\n};\n\n}  // namespace test\n}  // namespace clclass\n")
print("wrote", os.path.relpath(out), len(lines), "lines")
