// Every command the menus, the toolbar, the right-click menu and the keyboard
// shortcuts can run, by id (the WM_COMMAND id).

#ifndef CL_WINDOWS_COMMANDS_H
#define CL_WINDOWS_COMMANDS_H

enum Command {
	CMD_NONE = 0,
	// File
	CMD_NEW = 1000, CMD_OPEN, CMD_IMPORT, CMD_VERSIONS, CMD_NEW_TEMPLATE, CMD_SAVE_TEMPLATE, CMD_OPEN_SAMPLE, CMD_SAVE, CMD_SAVE_AS, CMD_EXPORT_IMAGE, CMD_EXPORT_V2, CMD_EXPORT_V1,
	CMD_PRINT, CMD_CLOSE_WINDOW, CMD_QUIT,
	// Edit
	CMD_UNDO, CMD_REDO, CMD_CUT, CMD_COPY, CMD_PASTE, CMD_DUPLICATE, CMD_DELETE, CMD_SELECT_ALL,
	CMD_ADD_GATE, CMD_GATE_SETTINGS, CMD_ROTATE, CMD_STRAIGHTEN, CMD_TIDY, CMD_TIDY_FLOW, CMD_TIDY_KEEP,
	CMD_TIDY_REVERT, CMD_TIDY_SWITCH, CMD_CONNECT_NEARBY, CMD_SAVE_PART, CMD_PREFERENCES,
	// View
	CMD_ZOOM_IN, CMD_ZOOM_OUT, CMD_ZOOM_FIT, CMD_ZOOM_ACTUAL, CMD_DARK, CMD_PALETTE, CMD_STATUS_BAR,
	// Simulate
	CMD_RUNNING, CMD_STEP, CMD_SIM_VIEW, CMD_LOCK, CMD_TRUTH_TABLE, CMD_SCOPE,
	// Tabs
	CMD_NEW_TAB, CMD_CLOSE_TAB, CMD_REOPEN_TAB, CMD_RENAME_TAB, CMD_NEXT_TAB, CMD_PREVIOUS_TAB,
	// Help
	CMD_SHORTCUTS, CMD_TOUR, CMD_HELP, CMD_CHECK_UPDATES, CMD_ABOUT,
	// The right-click menu's Disconnect, and the recent files (CMD_RECENT + i).
	CMD_DISCONNECT,
	CMD_RECENT = 1900,
	CMD_RECENT_LAST = 1909,
};

#endif  // CL_WINDOWS_COMMANDS_H
